name: Main

on:
 push:
  branches:
   - feature1
   - main
   
 pull_request:
  branches:
  - main
  
 workflow_dispatch:
  
 
jobs:

# call test workflow   
  call-test-workflow:
   
   uses: ./.github/workflows/linter-test.yml

# call the build workflow
  call-build-workflow:
    permissions: 
      contents: read
      packages: write
    needs : call-test-workflow
    uses: ./.github/workflows/build.yml
    secrets: inherit
    
    
 

# call deploy to staging workflow
  call-deployStaging-workflow:
   needs: call-test-workflow
   uses: ./.github/workflows/deploy-staging.yml
 
 # call depoly ecs workflow
  #call-deployECS-workflow:
    #permissions:
      #contents: read
      #id-token: write
    #needs : call-deployStaging-workflow
    #uses: ./.github/workflows/ecs-deploy.yml
  
  
  
   
  
