name: Main

on:
 workflow_dispatch:
  
 
jobs:

# call the build workflow
  call-build-workflow:
    permissions: 
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    secrets: inherit
    
    
 # call test workflow   
  call-test-workflow:
   needs: call-build-workflow
   uses: ./.github/workflows/linter-test.yml

# call deploy to staging workflow
  call-deployStaging-workflow:
   needs: call-test-workflow
   uses: ./.github/workflows/deploy-staging.yml
 
 # call depoly ecs workflow
  call-deployECS-workflow:
    permissions:
      contents: read
      id-token: write
    needs : call-deployStaging-workflow
    uses: ./.github/workflows/ecs-deploy.yml
  
  
  
   
  
